[package]
name = "videas"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = "4"
actix-files="0.6.5"
chrono = { version = "0.4", features = ["serde"] }
markdown = "1.0.0-alpha.16"
log = "0.4.0"
env_logger = "0.11.1"
dotenvy = "0.15"
diesel = { version = "2.1.0", features = ["sqlite"] }
